services:
  album_extractor:
    build:
      context: .
    command: python src/main.py /data/tracks
    environment:
      - USERNAME=postgres
      - PASSWORD=postgres
      - SERVER=host.docker.internal
      - PORT=5432
      - DATABASE=analysis
    volumes:
      - c:/Users/kkiiza/Downloads/tracks:/data/tracks
