services:
  album_extractor:
    build:
      context: .
    command: python src/main.py /data/tracks
    environment:
      - USERNAME=$USERNAME
      - PASSWORD=$PASSWORD
      - SERVER=host.docker.internal
      - PORT=$PORT
      - DATABASE=$DATABASE
    volumes:
      - ~/Downloads/Carlene_Davis_Come_To_Me_Softly:/data/tracks
